export default {
    FORMS_SEND: 'Send',
    FORMS_CANCEL: 'Cancel',
    FORMS_LOADING: 'Loading...',
    FORMS_CONFIRM: 'Are you shure? All not submitted data will be erased...',
    FORMS_MULTIBLOCK_ADD: '+ add',
    FORMS_SELECT_LABEL: 'Select a value',
    FORMS_SELECT_PLACEHOLDER: 'Pick a value',
    FORMS_SELECT_AJAX_PLACEHOLDER: 'Start typing...',
    FORMS_SELECT_EMPTY: 'Nothing found',
    FORMS_SELECT_ADD_TAG: 'Add new value',
    FORMS_UPLOAD_DROP: 'Drag and drop file or',
    FORMS_UPLOAD_ADD: 'Add file',
    FORMS_UPLOAD_FORMAT: 'File formats only',
    FORMS_UPLOAD_SIZE: 'Size of files no more then',
    FORMS_UPLOAD_REMOVE: 'Remove file',
    FORMS_UPLOAD_LOADING: 'Uploading',
    FORMS_UPLOAD_DONE: 'Finished',
    FORMS_UPLOAD_ERROR: 'Error',
    FORMS_UPLOADER_EXTENSION_ERROR: 'File %s has wrong extension',
    FORMS_UPLOADER_SIZE_ERROR: 'File %s is too big',
    FORMS_EDITOR_VISUAL: 'Visual',
    FORMS_EDITOR_CODE: 'Code',
    FORMS_DATERANGE_START_LABEL: 'Start date',
    FORMS_DATERANGE_END_LABEL: 'End date',
    FORMS_DATEPICKER: {
        days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        daysFull: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thirsday', 'Friday', 'Saturday'],
        months: [
          'January',
          'February',
          'March',
          'April',
          'May',
          'June',
          'July',
          'August',
          'September',
          'October',
          'November',
          'December',
        ],
        today: 'Today',
        clear: 'Clear',
        close: 'Close'
    } 
}
